image:
- Ubuntu1804

stack: python 3.7

clone_depth: 25

build: off

init:
- sh: sudo apt -q update > /dev/null
- sh: sudo apt -yq install liblzma-dev > /dev/null
# liblzma-dev is needed by Appveyor Ubuntu1804 to install Python packages in devel mode, even when only using stdlib.

install:
# pip can't be in init, wrong python version
- git clone https://github.com/mesonbuild/meson.git ../meson
- python -m pip install -e ../meson
- python install_prereqs.py > /dev/null

before_test:
- python -m pip install -e .[tests]
- meson build

test_script: meson test -C build
