language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: CC=gcc-6 FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: ['gcc-6', 'gfortran-6','liblapack-dev','libmumps-dev','libopenmpi-dev']

before_install:
- git clone https://github.com/mesonbuild/meson ../meson
- python -m pip install -e ../meson
- curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

install:
- pip install -e .[tests]
- meson build

script: meson test -C build --suite unit
